components/common/button/Button.vue
components/common/button/ButtonBack.vue
components/footer/Footer.vue
components/header/AccountDropdown.vue
components/header/NetworkDropdown.vue
components/modal/LegalNotice.vue
pages/assets.vue
pages/receive-methods.vue
store/onboard.ts
views/transactions/Transfer.vue

Some more UI/style fixes.

---

views/transactions/Deposit.vue

- Reset and update fee after allowance call
- Watch if allowance status changes to update fees

fix(chore): added fix to update the gas fee after submitting an allowance

---

composables/zksync/deposit/useTransaction.ts

- Gas limit wasn't high enough for bridging tokens, remove gas limit if token is erc20
https://github.com/user-attachments/assets/c61cc850-21c1-4c41-9a0a-1c31088bd427

fix(chore): unset gas limit if token is erc20

---

data/networks.ts
store/network.ts

- Created function to set default chain based on current host

Feat - set default network based on current hostname

---

components/token/TokenSelectModal.vue
views/transactions/Deposit.vue
views/transactions/Transfer.vue

- Added check to remove SOPH filter if current network is testnet;
- Fix token select modal text (removed zkSync mention)

feat: remove SOPH filter for testnet + fix text message

---

composables/transaction/useWithdrawalAllowance.ts
composables/zksync/deposit/useTransaction.ts
composables/zksync/useFee.ts
composables/zksync/useTransaction.ts
hyperchains/config.json
views/transactions/Deposit.vue
views/transactions/Transfer.vue
views/transactions/WithdrawalSubmitted.vue

Adding support for USDC token.
Also, fixing "sophon-mainnet" chain name (should be "sophon"). Please double check this since I'm not tht familiar with this codebase and I could be wrong @CryptoMan0x @saviotx @consvic

Support USDC token

---

data/mainnet.ts
types/index.d.ts
views/transactions/Deposit.vue

- Added list in deposit page to blacklist tokens from getting merged

feat: add blacklisted tokens list per chain

---

store/zksync/ethereumBalance.ts

Issue: RPC endpoint can be overloaded sometimes, resulting in an intermittent behaviour for getting L1 balances.
Fix: Added a retry method and, in case everything fails, we return token amount 0 so that the app does not break.

fix: add retry method for fetching L1 balances

---

components/header/Header.vue
components/transaction/EthereumTransactionFooter.vue
components/transaction/TransactionFooter.vue
components/transaction/buttonUnderline/ConfirmTransaction.vue
components/transaction/buttonUnderline/ContinueInWallet.vue
data/mainnet.ts
views/transactions/Deposit.vue
views/transactions/WithdrawalSubmitted.vue

- Added Noon token address to blacklisted tokens
- Changed route for sophon logo to be home page

Fix: final shipping changes

---

composables/zksync/deposit/useFee.ts

Refactor gas price retrieval in `useFee.ts` to utilize `Web3Provider`

Fix: deposit fee estimation

---

utils/ecosystem.ts

Enable NOVA card:
- add link
- set isComingSoon false

feat: add NOVA link

---

views/transactions/Deposit.vue

- Check if network is the same as it should be to estimate fee

fix: hide the fee if in wrong network

---

views/transactions/Deposit.vue

- Only display common alerts if on the same chain

Fix - chain common alerts

---

store/onboard.ts
views/transactions/Deposit.vue

Add support for rainbow wallet switching network to sophon

feat: add switch network on rainbow wallet

---

components/common/button/AddToWalletButton.vue
components/token/TokenBalance.vue
components/token/TokenLine.vue
components/token/TokenSelectModal.vue
composables/useWalletClient.ts

- Created component to add token from list to wallet

feat: add token to wallet on modal

---

pages/home.vue
utils/ecosystem.ts

- Add new categories
- Add desktop version of the filter buttons

Feat: add ecosystem's categories filter

---

views/transactions/Deposit.vue
views/transactions/Transfer.vue

- Check for token balance and input amount before estimating fee

fix: only estimate if both balance and amounts entered are >0

---

components/transaction/TransactionProgress.vue

feat: better label + new link to let user know about processing time

---

composables/layerzero/deposit/useFee.ts
composables/layerzero/deposit/useTransaction.ts
composables/layerzero/oftHelperAbi.ts
composables/layerzero/useFee.ts
composables/layerzero/useTransaction.ts
composables/transaction/useWithdrawalAllowance.ts
views/transactions/Deposit.vue
views/transactions/Transfer.vue

Add L0 withdrawal for supported tokens

feat: add L0 withdrawal

---

components/transaction/TransactionProgress.vue
hyperchains/config.json
views/transactions/Deposit.vue
views/transactions/Transfer.vue
views/transactions/WithdrawalSubmitted.vue

- Disable button on Bridge click
- Change progress copy
- Add explorer link

fix: layerzero transaction progress

---

hyperchains/config.json

fix: add hashed susn address

---

composables/usePortalRuntimeConfig.ts
hyperchains/config.json
nuxt.config.ts
package-lock.json
package.json
store/ethereumBalance.ts
store/zksync/ethereumBalance.ts
types/index.d.ts

- Removed ANKR token and ankr token fetching implementation
- Replaced for alchemy sdk, added an optional alchemy api key
- Changed logic for using api balances instead of rpc

feat: fetch balances using alchemy sdk

---

store/zksync/withdrawals.ts

Increase withdrawal limit time from 31 days to 180 days (6 months)

feat: increase withdrawal fetch time limit

---

store/ethereumBalance.ts

Tokens have the right flag
Fee working correctly

fix: check for token to actually be oft

---

pages/home.vue
pages/transfers.vue
views/transactions/Deposit.vue

feat(SOP-515): add upgrade notice on transfers + bridge pages

---

pages/transfers.vue
views/transactions/Deposit.vue

Dev -> Main

---

data/customBridgeTokens.ts

Remove bridgingDisabled flag from wstETH token

fix: enable wstETH deposit 

---

pages/transfers.vue
views/transactions/Deposit.vue

Add mainnet upgrade step 2 banner

feat: add upgrade banner

---

data/mainnet.ts
pages/transfers.vue
views/transactions/Deposit.vue

- Add stETH to `BLACKLISTED_TOKENS` since we should not support stETH deposits 
- Remove upgrade banners

[SOP-569] Feat: add stETH to BLACKLISTED_TOKENS

---

data/customBridgeTokens.ts

- Remove wstETH from custom tokens list

Fix: remove custom wstETH

---

nuxt.config.ts

- ✅ feat(security): add HTTP security headers to the application
- Implemented Content-Security-Policy to prevent iframe embedding
- Added X-Frame-Options for clickjacking protection
- Configured X-Content-Type-Options to prevent MIME type sniffing
- Set Referrer-Policy to control referrer information
- Added Permissions-Policy to restrict sensitive browser features
- Implemented Strict-Transport-Security for HTTPS enforcement
The PR adds critical security headers to all routes via Nuxt 3's Nitro engine configuration. These headers follow security best practices to protect users from common web vulnerabilities including:
- 🔒 Clickjacking attacks (frame-ancestors restriction)
- 🕵️ MIME type confusion exploits
- 🔗 Referrer leakage across origins
- 📹 Unauthorized access to sensitive device …

[SOP-587] feat: security headers

---

views/transactions/Deposit.vue

- Fix OFT "Another Sophon account" address on deposit

fix: oft to address

---

composables/layerzero/useFee.ts
composables/zksync/deposit/useTransaction.ts
views/transactions/Deposit.vue
views/transactions/Transfer.vue

- Fix L0 fee estimation on Transfers
- Removed totalComputeAmount check to trigger fee estimation on deposits
- Fix check to correctly trigger allowances checks

[SOP-622] fix: general fixes on oft flows

---

hyperchains/config.json
store/zksync/ethereumBalance.ts

- Use full hash in config addresses
- Compare addresses with uppercase
**Balances**
**Bridging**

Hotfix - address comparison + full hash addresses in config

---

hyperchains/config.json
store/zksync/ethereumBalance.ts

- Use full hash in config addresses
- Compare addresses with uppercase

Fix - token merge balances

---

composables/layerzero/useFee.ts
views/transactions/Transfer.vue

- Only call oft specific functions when withdrawing
- isApproved has some lag so it might not return the real value after approving allowance

Hotfix: OFT transfers

---

composables/layerzero/useFee.ts
views/transactions/Transfer.vue

- Only call oft specific functions when withdrawing
- isApproved has some lag so it might not return the real value after approving allowance

[SOP-718] Fix - OFT transfers

---

composables/zksync/useTransaction.ts

- Enable SOPH transfers/withdrawals by removing paymaster usage when selected token is SOPH

[SOP-580] feat: enable SOPH transfers

---

composables/zksync/useTransaction.ts

Fixed a critical issue where send transactions were failing with a viem error:
```
could not coalesce error (error={ "code": -32603, "message": "An internal error was received.\n\nDetails: Cannot read properties of null (reading 'coinId')\nVersion: viem@2.30.1" }, payload={ "id": 6, "jsonrpc": "2.0", "method": "eth_getTransactionCount", "params": [ "0x...", "pending" ] }, code=UNKNOWN_ERROR, version=6.13.5)
```
The error occurred when `signer.sendTransaction()` internally called `getTransactionCount()` to retrieve the transaction nonce. This internal call was causing a viem compatibility issue with the provider chain, specifically when reading `coinId` properties.
- **Manual nonce handling**: Added explicit nonce retrieval before transaction submission to avoid the problematic internal …

feat: update okx tx send feature

---

store/zksync/withdrawals.ts
views/transactions/Transfer.vue

chore: dev -> main
